[std."0.1.0"]
link = "https://github.com/shareui/yuki-stdlib/releases/download/0.1.0/stdlib.tar.zst"

[rt."0.1.0"]
x86_64-unknown-linux-gnu = "https://github.com/shareui/yuki-stdlib/releases/download/0.1.0/yukino-runtime.a"
